### ISSUE TITLE
Not valid json format

### ISSUE THREAD

**Issue by otakuf** [ChristianWitts/spamhaus#1]
I`ll check json output from example on validator: https://jsonformatter.curiousconcept.com/
Multiple JSON root elements, need one root item.

`{
    "description": "Spamhaus Block List (SBL)  test record",
    "domain_name": "spamhaus.org",
    "incident_id": "SBL2",
    "ip_address": "127.0.0.2/32",
    "timestamp": "2016-04-02T18:34:00"
},
{
    "description": "Spamhaus DROP (Don't Route Or Peer) and EDROP test record",
    "domain_name": "spamhaus.org",
    "incident_id": "SBL9",
    "ip_address": "127.0.0.9/32",
    "timestamp": "2016-04-02T17:57:00"
},
{
    "description": "SBL TEST ADDRESS - sbl.crynwr.com",
    "domain_name": "spamhaus.org",
    "incident_id": "SBL230",
    "ip_address": "192.203.178.107/32",
    "timestamp": "2001-08-01T08:51:00"
}`

**Comment by ChristianWitts** [comment]
Fixed in #2
